### ISSUE TITLE
Authentication for Chart Repository

### ISSUE THREAD

**Issue by Soumyakulkarni5** [bitovi/github-actions-deploy-eks-helm#11]
Are you considering enabling authentication for the chart repository?

**Comment by LeoDiazL** [comment]
Hey @Soumyakulkarni5 

We have an update in a [PR](https://github.com/bitovi/github-actions-deploy-eks-helm/pull/12) to this action in order to introduce auth for helm charts.
You can test it out by changing your workflow yaml line to use a specific branch like this
```
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@11-authentication-for-chart-repository
```
And now you can add all this options:
```
    ca-file
    cert-file
    key-file
    insecure-skip-tls-verify
    pass-credentials
    password
    username
```
Let us know if we can do anything to assist.
