### ISSUE TITLE
Authenticate using Github's OIDC provider

### ISSUE THREAD

**Issue by macmiranda** [bitovi/github-actions-deploy-eks-helm#13]

**Comment by PhillypHenning** [comment]
So I think that there are already actions that take care of this, the real need from this action would be to respect any prior loading that may have taken place. 

In order to not change how we do things today I propose 2 ideas; 

1. Add a property to the action that specifies if the cloud provider credentials were previously loaded
2. Add a null check in the action, if the cloud credentials are already loaded, do not override them

**Comment by macmiranda** [comment]
If fact, if you made the access key id and secret variables optional, aws cli would just follow the default credential chain and attempt to authenticate using any other stored credentials.

**Comment by LeoDiazL** [comment]
Hey @macmiranda 

We have an update in a https://github.com/bitovi/github-actions-deploy-eks-helm/pull/15 to this action in order to make AWS credentials optional.

You can test it out by changing your workflow yaml line to use a specific branch like this
```
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@13-authenticate-using-githubs-oidc-provider
```

Let us know how it goes! Thanks!
