### ISSUE TITLE
Support local helm charts, i.e. tgz package or OCI-based registries

### ISSUE THREAD

**Issue by macmiranda** [bitovi/github-actions-deploy-eks-helm#14]

**Comment by LeoDiazL** [comment]
Hey @macmiranda,

Can you clarify the need here?  We have 2 possible approaches depending on the need.

One approach is to make the aws auth credentials optional, so that the github runner’s AWS credentials (if you’re using a self-hosted runner, for example) are used to pull images.  (similar to the desired approach for [this issue](https://github.com/bitovi/github-actions-deploy-eks-helm/issues/13))
It’s not clear how that approach would be helpful for the images that are specified by helm to be pulled from a kubernetes cluster.

Typically, with kubernetes, you would use ImagePullSecrets (most helm charts specify this) or you’d specify it in your pod spec for your own helm charts.  Here’s some more info on how that works:
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

In the latter case, you could instead provide EKS worker nodes with a role that has access to the ECR registry rather than specifying imagepullsecrets.

Which use-case did you have in mind (github runner credentials, or EKS cluster credentials)?

**Comment by macmiranda** [comment]
Hi @LeoDiazL,

We publish our Helm charts as OCI images to ECR and use our deploy action to pull the chart before installing it. I guess what I'm really trying to say is that we would welcome support for local Helm charts. Given that the image was already fetched in a different step, then we could use it as an input here.
I don't know exactly I why I thought that the action should download the image too, but that could be easily done outside of this action.
I'll change the title to be more precise

**Comment by mickmcgrath13** [comment]
There is a `$DEPLOY_CHART_PATH` environment variable used to determine where helm finds the chart:
https://github.com/bitovi/github-actions-deploy-eks-helm/blob/main/deploy.sh#L99

It is provided by action via `chart-path`:
https://github.com/bitovi/github-actions-deploy-eks-helm/blob/main/action.yaml#L81

So if your action runner is set up with access to your ECR registry (i.e. rbac via IAM, for example),  for OCI, as per [helm docs](https://helm.sh/docs/topics/registries/#other-subcommands), you should be able to do something like:
```
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
      with:
        chart-path: oci://localhost:5000/helm-charts/mychart
```

which would result in something like the following command:
```
helm upgrade oci://localhost:5000/helm-charts/mychart
```


Similarly, to install from a file instead (i.e. if you've downloaded the chart in a previous step), you should be able to provide a relative path to the local chart like:
```
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
      with:
        chart-path: relative/path/to/mychart
```



This doesn't support `helm login`. As previously discussed, if the github action runner is a custom runner that is set up with access to your internal ECR registry, this step would not be necessary.

If you're looking to skip the download step as part of your workflow and have this action do it instead, then this issue would turn into a need to support `helm login`.



@macmiranda Does that help?  Do you think this github action should support `helm login` to support your use-case?

**Comment by mickmcgrath13** [comment]
no problem!

I'll close this ticket.  Please re-open if you feel it's incomplete.

Also, we now have another issue to track support of `helm login` (though I'm not sure when Bitovi will be able to get to it).  PRs welcome! ;)
